### ISSUE TITLE
Impossible to set a public album

### ISSUE THREAD

**Issue by sanghin** [ltribolet/Lychee#38]
### Detailed description of the problem [REQUIRED]

When we set a album as public a empty password will be set 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to an album
2. Click on the visibility icon
3. Check public (and public access only)
4. Logout and try to access the album
5. A password is required and the lock icon is display on the Album

**Screenshots**

**Comment by ltribolet** [comment]
Duplicate with #37 ?

**Comment by sanghin** [comment]
Nope this one is different, when you select public and only public it will set an empty password

**Comment by ltribolet** [comment]
I think I've addressed it in #39

**Comment by ltribolet** [comment]
The problem will still remain because of #37 though.

**Comment by ltribolet** [comment]
As I thought it has been fixed by #39
